# Database 설정
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:

# H2 Database Dialect Setting
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect